target 'FileInfoExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FileInfoExtension

  target 'FileInfoExtensionTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'FileInfoExtensionUITests' do
    # Pods for testing
  end

end

target 'FileInfoFinderExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FileInfoFinderExtension

end
